### ISSUE TITLE
INI File format parser issues

### ISSUE THREAD

**Issue by xrem** [FRedEnergy/itmo-oop-tasks#3]
This can be simplified
https://github.com/FRedEnergy/itmo-oop-tasks/blob/462e8a0661c991c6d3c211409297273c06c6580b/Lab3/Program.cs#L13-L18
To:
```c#
if (!File.Exists(fileName)) {
    Console.WriteLine(fileName + " not found");
    return;
}
var dataFile = IniDataFile.Parse(fileName);
```

---
Accoring to [MS naming conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions), methods should use [UpperCamelCase](https://ru.wikipedia.org/wiki/CamelCase)

Please fix this: 
https://github.com/FRedEnergy/itmo-oop-tasks/blob/462e8a0661c991c6d3c211409297273c06c6580b/Lab3/IniDataSection.cs#L19

https://github.com/FRedEnergy/itmo-oop-tasks/blob/462e8a0661c991c6d3c211409297273c06c6580b/Lab3/IniDataSection.cs#L24

p.s. And yet again, IDE should show suggestions like this:
![image](https://user-images.githubusercontent.com/7121898/64918257-6922af80-d7a4-11e9-9b1b-ec2960831cba.png)
Do not ignore them.

---
Please take care of culture of numbers with floating-point. 
![image](https://user-images.githubusercontent.com/7121898/64918297-04b42000-d7a5-11e9-962e-43aa83c79e39.png)

Please use explicit casting from double to string with a culture specification, like so:
```c#
var d = 3.123456789;
Console.WriteLine(d.ToString("F2", CultureInfo.InvariantCulture));
```

I would not advise you to implement `string to anything` template method in this program.
Try to get rid of `Convert.ChangeType` and replace it this specific calls for double and ints (i.e. double.TryParse and int.TryParse)
https://stackoverflow.com/questions/30819791/restrict-generic-t-to-specific-types
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/types/casting-and-type-conversions

---
https://github.com/FRedEnergy/itmo-oop-tasks/blob/462e8a0661c991c6d3c211409297273c06c6580b/Lab3/IniDataFile.cs#L11-L15
Looks like a leak of verification that section do exists.

If you like syntax sugar, you can use [Null coalescing operator](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/null-coalescing-operator):
```c#
// ...
get => Sections.GetValueOrDefault(key, null) ?? throw new SectionNotFoundException("...");
// ..
```
p.s. also, looks like we do not want to have a public setter.

---

Could you create more exceptions for specific cases?
`IniFormatException` for formating errors is fine, but we need at least one for cast exceptions and one more for handling invalid structure of fine (i.e. SectionNotFound)

**Comment by abvadabra** [comment]
Fixed most of the issues in df085ec3f1135232a982d0b5e8334eca7f386dbb however I do not agree with all suggested improvements.

First of all, I am not sure why replacing `Convert.ChangeType` with manual type checking for ints, doubles, floats, etc is any better since we will be just repeating code which is already in impemented in standart library. I understand that the point of task is to teach how to work with types and generics but in that case `Convert.ChangeType` just feels like a much better and cleaner solution :p

I also hasn't done anything about the culture of numbers since that issue is just in a demonstration code and doesn't directly affects the API or any logic.

I have added two more exception: `IniTypeException` for cases when invalid type is provded to `Get<T>` function and `IniUnknownSectionException` for cases when API user tries to extract invalid section. 

I also fixed some other minor problems which have been pointed out in the issue.
